### ISSUE TITLE
Open ATV 6.2 Fan

### ISSUE THREAD

**Issue by loxel** [MCelliotG/GlamourAuraFHD-ATV-skin#24]
Hello
The Fan rotation is not visible in the skin
There is only a message
"**No Fan detected**"
Thanks

Vu+ Duo2

**Comment by MCelliotG** [comment]
I don't own a receiver with a built-in fan, so I don't know if the Fan speed works, so please if you can log in to telnet and tell me what this command shows
cat /proc/stb/fp/fan_speed

Thanks in advance!

**Comment by loxel** [comment]
Hi
Command shows 
root@vuduo2:~# cat /proc/stb/fp/fan_speed
**1420 rpm**
Thanks

**Comment by MCelliotG** [comment]
Thank you so much, I'll revise the code!
And since you can get these commands, let's make a complete report, so could you kindly provide me the output of these commands too?
/proc/stb/fp/fan_vlt
/proc/stb/fp/fan_pwm

**Comment by loxel** [comment]
root@vuduo2:~# /proc/stb/fp/fan_vlt
-bash: /proc/stb/fp/fan_vlt: Permission denied

**Comment by loxel** [comment]
root@vuduo2:~# /proc/stb/fp/fan_pwm
-bash: /proc/stb/fp/fan_pwm: Permission denied

**Comment by MCelliotG** [comment]
Sorry I meant 
cat /proc/stb/fp/fan_vlt
cat /proc/stb/fp/fan_pwm

**Comment by loxel** [comment]
ok ,no problem :)
root@vuduo2:~# cat /proc/stb/fp/fan_vlt
**ff**

root@vuduo2:~# cat /proc/stb/fp/fan_pwm
**7e**

**Comment by MCelliotG** [comment]
OK, thank you! Now, try this!
[https://mega.nz/#!eE82xIqR!mpnCFgr7T6c8XCwVMoeCAJ4_4TPHPmxSVouGeWQZzXE](url)
Get the above file it's a zip containing a new GlamourExtra.py converter and a new skin.xml.
Please use an FTP client and push the GlamourExtra file to /usr/share/enigma2/python/Components/Converter folder (replace files if necessary)
and the skin.xml to /usr/share/enigma2/GlamourAuraFHD-ATV folder (also replace file).

Then through telnet
killall -9 enigma2

and report back to me what is shown in the fan info (a screenshot would help even more)!

**Comment by loxel** [comment]
Everything is ok now :)
https://naforum.zapodaj.net/6490f86c652a.png.html
Thanx

**Comment by MCelliotG** [comment]
Perfect, let's now push the changes!!! Thank you so much for your feedback!
