### ISSUE TITLE
build broken

### ISSUE THREAD

**Issue by atvcaptain** [MCelliotG/GlamourAuraFHD-ATV-skin#43]
|   File "/home/oe1/atv63/build-enviroment/builds/openatv/release/dags7335/tmp/work/all-oe-linux/enigma2-plugin-skins-glamour-aura-fhd-atv/8.x+gitAUTOINC+8d4ef0213f-r0/git/usr/lib/enigma2/python/Components/Renderer/GlamRoll.py", line 56
|     self.text = txttmp.encode("utf8","ignore").replace("\n","").replace("\r"," ").
|                                                                                  ^
| SyntaxError: invalid syntax

**Comment by MCelliotG** [comment]
Thank you for notifying me. I just fixed it!
